name: energy_manager_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter  
  riverpod_lint: ^2.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
